# Inference Proxy 設定ファイル
# このファイルは config.yaml としてコピーして使用してください

# サービス設定
# 複数のサービスを設定できます
services:
- name: text-generation-model # サービス名
  image: ai-model:latest # Dockerイメージ
  port: 8000 # ポート番号

- name: image-generation-model # サービス名
  image: image-model:latest # Dockerイメージ
  port: 8001 # ポート番号

# ログ設定
logging:
  output_dir: /var/log/ai-proxy # ログ出力ディレクトリ
  level: INFO # ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)

# 環境変数によるオーバーライド:
# INFERENCE_PROXY_SERVICE_PORT - すべてのサービスのポート番号をオーバーライド
# INFERENCE_PROXY_LOG_LEVEL - ログレベルをオーバーライド 
